from sage.all import * 
from primefac import primefac
from sympy import isprime

# generating polynomials f and primes p, where f has a root of a specified order modulo q is easy. 
# Approaches include: (1) given  f, find a suitable q. (2) given q, find a suitable f 
# The original paper follows (1), but since we need to satisfy the properties below, we first generate a prime q
# and then go with (2) 

# Desired properties : 
# 1. Is irreducible in Z[x]
# 2. Is non-cyclotomic
# 3. All of its roots are of small order in Z_q[x]
# 4. Splits completely in Z_q[x] 

# for some prime q 


# Step 1 : find a prime q, for which Z_q has elements of small order
def generate_prime(n=5, max_k = 100):
    M = prod(primes_first_n(n))
    while True:
        p = randint(1, max_k) * M + 1
        if isprime(p):
            return p 

def irreducible_poly_mod_q(q, max_order, n):

    orders = list(dict.fromkeys(primefac(q-1)))

    _n = n + 1
    _order_id = 0

    #for each order < max_order, find  k = order elements with order = order in Z_q 
    roots = []
    while _n > 0:
        order = orders[_order_id]
        c = 2 
        for c in range(2, q):
            if pow(c, order, q) == 1:
                break 

        #get the subgroup generated by c 
        roots += [pow(c, i, q) for i in range(1, min(order, _n))]

        _n -= (order - 1)
        _order_id += 1 

    R = PolynomialRing(ZZ, 'x')
    R_q = PolynomialRing(Zmod(q), 'x')
    x = R.gen()
    f_q = prod([(x-a) for a in roots])

    #find an irreducible polynomial in Z[x] which is equivalent to f_q in Z_q[x] 
    while True:
        h = R.random_element(degree=n-1)
        f = f_q + q*h

        if f.is_irreducible():
            assert(R_q(f) == f_q) 
            return f 


if __name__ == "__main__":
    q =  generate_prime(n = 5, max_k = 50)
    R_q = PolynomialRing(Zmod(q), 'x')

    print("q = ", q) 

    #find a polynomial 
    f = irreducible_poly_mod_q(q, max_order = 11, n = 9)

    print(f"f(x) = {f}\n")

    print(f"f(x) = {R_q(f)} (mod {q})\n")

    print(f"[factorized] f(x) = {R_q(f).factor()} (mod {q})\n")

    print("\n=== Orders of roots ===\n")

    for root, _, in R_q(f).roots():
        print(f"root : {root}, order : {Zmod(q)(root).multiplicative_order()}")

